name: run main.py

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/2 * * * *"

jobs:
  copyassignments:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          WEB_CAL: ${{secrets.WEB_CAL}}
        run: python CaltoNotion.py

      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main
  # copydescriptions:
  #   runs-on: ubuntu-latest
  #   needs: copyassignments

  #   steps:
  #     - name: checkout repo content
  #       uses: actions/checkout@v2 # checkout the repository content

  #     - name: setup python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10" # install the python version needed

  #     - name: install python packages
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #     - name: Installing package list
  #       run: apt list --installed
  #     - name: Removing previous chrome instances on runner
  #       run: sudo apt purge google-chrome-stable
  #     - name: Install xvfb
  #       run: sudo apt-get install xvfb
  #     - name: execute py script # run main.py
  #       env:
  #         NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
  #         WEB_CAL: ${{secrets.WEB_CAL}}
  #       run: python importdetails.py
